CREATE DATABASE DB
USE DB

CREATE TABLE VEZIFE(
ID  INT  PRIMARY KEY IDENTITY,
VEZIFE NVARCHAR (50)
)
INSERT INTO VEZIFE
VALUES('SELLER1')
INSERT INTO VEZIFE
VALUES('SELLER2')
DROP TABLE ISHCHI

CREATE TABLE ISHCHILER(
ID  INT  PRIMARY KEY IDENTITY,
MKOD NVARCHAR (50),
SAAD NVARCHAR (255),                  
VEZIFEID INT FOREIGN KEY REFERENCES VEZIFE(ID),
SALARY INT
)
INSERT INTO ISHCHILER
VALUES('A','CHRIS SMITH MARK',2,500)
INSERT INTO ISHCHILER
VALUES('B','TOM WILLIAMS LEO',1,650)



CREATE TABLE FILIAL(
ID  INT PRIMARY KEY IDENTITY,
FILIAL NVARCHAR (50)
)
INSERT INTO FILIAL
VALUES('BAKU')
INSERT INTO FILIAL
VALUES('LANKARAN')

CREATE TABLE PRODUCT(
ID  INT PRIMARY KEY IDENTITY,
NAME NVARCHAR (50),
ALISHQIYMET FLOAT,
SATISHQIYMET FLOAT
)
INSERT INTO PRODUCT
VALUES('DRESS',30,42)
INSERT INTO PRODUCT
VALUES('T-SHIRT',21,32)
INSERT INTO PRODUCT
VALUES('HAT',19,25)

CREATE TABLE SALE(
ID  INT PRIMARY KEY IDENTITY,
PRODUCTID INT REFERENCES PRODUCT(ID),
ISHCHIID INT REFERENCES ISHCHILER(ID),
FILIALID INT REFERENCES FILIAL(ID),
DISCOUNT FLOAT,
DATETIME DATE     
)
DROP TABLE SALES
INSERT INTO SALE
VALUES(1,1,1,20,'2022-07-08')
INSERT INTO SALE
VALUES(2,2,2,10,'2022-07-10')

--QUERY1
SELECT COUNT(ISHCHILER.ID) 'ISHCHILERIN SAYI' FROM ISHCHILER

--QUERY2
SELECT SAAD,SALARY FROM ISHCHILER ORDER BY SALARY DESC

--QUERY3
SELECT NAME,SATISHQIYMET FROM PRODUCT ORDER BY SATISHQIYMET DESC

--QUERY4
SELECT  DATETIME 'SATISH TARIXI',NAME 'PRODUCT ADLARI' FROM SALE 
JOIN PRODUCT
ON
PRODUCTID=PRODUCT.ID
ORDER BY DATETIME ASC

--QUERY5
SELECT ISHCHILER.SAAD 'ISHCHILER',VEZIFE.VEZIFE 'VEZIFELER' FROM ISHCHILER
JOIN VEZIFE
ON 
VEZIFE.ID=VEZIFEID